/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stackof_calljni_JniLib */

#ifndef _Included_com_stackof_calljni_JniLib
#define _Included_com_stackof_calljni_JniLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stackof_calljni_JniLib
 * Method:    callToCpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_stackof_calljni_JniLib_callToCpp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
